# Generated by Django 4.2.1 on 2023-05-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeProject', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
    ]
